/**
 * The public board's arrangement rules.
 *
 * `src/components/format/board.ts` is what the Teams, Schedule, Bracket and
 * Results tabs are built out of, and every one of its functions is a display
 * decision that has been got wrong at least once in a tournament board
 * somewhere: which of two numbers is the score, whether a drawn series counts
 * as finished, which day 00:30 belongs to, and whether two teams knocked out in
 * the same round finished fifth and sixth or joint fifth.
 *
 * The fixtures are real stages generated by `src/lib/bracket.ts` and resolved
 * by `src/lib/format-resolve.ts` rather than hand-written objects, so a change
 * to the engine that would break the board shows up here rather than in a
 * browser.
 *
 * The suite pins `TZ=Europe/Budapest` (see `vitest.config.ts`), which is what
 * makes the timezone assertions below mean anything at all.
 */

import { describe, expect, it } from "vitest";
import { generateStage } from "@/lib/bracket";
import { planBlocks } from "@/lib/format-schedule";
import { type ResolvedMatch, resolveMatches } from "@/lib/format-resolve";
import {
  blankRecords,
  drawSeries,
  makeTeams,
  playStage,
  winSeries,
} from "@/lib/__tests__/format-helpers";
import {
  championOf,
  gameLine,
  gamesPlayed,
  groupByDay,
  hasBracketShape,
  matchHasResult,
  matchTone,
  matchToneNote,
  playedGames,
  podiumEntries,
  refereesOf,
  resultsLog,
  seriesScore,
  tableStarted,
  upNext,
} from "../board";
import { dayBySlot } from "../columns";

/* ------------------------------------------------------------------ */
/* Fixtures                                                           */
/* ------------------------------------------------------------------ */

/** An eight-team double elimination, untouched. */
function blankEight(): ResolvedMatch[] {
  const stage = generateStage("double_elim", 8, {});
  return resolveMatches({ stage, matches: blankRecords(stage), teams: makeTeams(8) });
}

/** A match built from scratch, for the cases a generated one cannot produce. */
function fakeMatch(over: Partial<ResolvedMatch> = {}): ResolvedMatch {
  return {
    slot: "x",
    bestOf: 1,
    teamAId: "t1",
    teamBId: "t2",
    sourceA: null,
    sourceB: null,
    scheduledAt: null,
    finishedAt: null,
    durationMin: null,
    winnerOverrideId: null,
    games: [],
    round: 1,
    phase: 1,
    bracket: "upper",
    group: null,
    label: "Match",
    displayLabel: "Match",
    roundLabel: "Round",
    note: null,
    elimination: true,
    modes: [],
    nameA: "Team 1",
    nameB: "Team 2",
    gamesWonA: 0,
    gamesWonB: 0,
    winner: null,
    loser: null,
    status: "pending",
    needsDecision: false,
    skipped: false,
    ...over,
  };
}

function game(over: Partial<ResolvedMatch["games"][number]> = {}) {
  return {
    index: 0,
    mode: "convoy",
    map: "",
    referee: "",
    scoreA: 0,
    scoreB: 0,
    played: false,
    ...over,
  };
}

/* ------------------------------------------------------------------ */
/* Series arithmetic                                                  */
/* ------------------------------------------------------------------ */

describe("seriesScore", () => {
  it("prints a Bo1's map score, not 1–0", () => {
    const match = fakeMatch({
      bestOf: 1,
      games: [game({ scoreA: 3, scoreB: 1, played: true })],
      gamesWonA: 1,
      gamesWonB: 0,
    });
    expect(seriesScore(match)).toEqual({ a: 3, b: 1 });
  });

  it("leaves an unplayed Bo1 at nothing rather than showing a typed-in score", () => {
    const match = fakeMatch({ bestOf: 1, games: [game({ scoreA: 3, scoreB: 1 })] });
    expect(seriesScore(match)).toEqual({ a: 0, b: 0 });
  });

  it("prints maps won for anything longer", () => {
    const match = fakeMatch({
      bestOf: 3,
      games: [
        game({ index: 0, scoreA: 3, scoreB: 1, played: true }),
        game({ index: 1, scoreA: 1, scoreB: 3, played: true }),
        game({ index: 2, scoreA: 3, scoreB: 2, played: true }),
      ],
      gamesWonA: 2,
      gamesWonB: 1,
    });
    expect(seriesScore(match)).toEqual({ a: 2, b: 1 });
  });
});

describe("playedGames and matchHasResult", () => {
  it("counts only the games actually ticked off", () => {
    const match = fakeMatch({
      bestOf: 3,
      games: [game({ index: 0, played: true }), game({ index: 1, scoreA: 3 })],
    });
    expect(playedGames(match)).toHaveLength(1);
    expect(matchHasResult(match)).toBe(true);
  });

  it("treats a card filled in but never ticked as nothing having happened", () => {
    const match = fakeMatch({ bestOf: 3, games: [game({ scoreA: 3, scoreB: 1 })] });
    expect(matchHasResult(match)).toBe(false);
  });

  it("counts a finished match even with no games, since an override can settle one", () => {
    expect(matchHasResult(fakeMatch({ status: "done", games: [] }))).toBe(true);
  });
});

describe("refereesOf", () => {
  it("keeps first-appearance order, trims, and never repeats a name", () => {
    const match = fakeMatch({
      games: [
        game({ index: 0, referee: " Zoe " }),
        game({ index: 1, referee: "Alex" }),
        game({ index: 2, referee: "Zoe" }),
        game({ index: 3, referee: "   " }),
      ],
    });
    expect(refereesOf(match)).toEqual(["Zoe", "Alex"]);
  });
});

describe("gameLine", () => {
  it("names the mode and the map together", () => {
    expect(gameLine({ mode: "domination", map: "Midtown" })).toBe("Domination · Midtown");
  });

  it("falls back to whichever of the two was recorded", () => {
    expect(gameLine({ mode: "convoy", map: "" })).toBe("Convoy");
    expect(gameLine({ mode: "", map: "Midtown" })).toBe("Midtown");
    expect(gameLine({ mode: "", map: "" })).toBe("");
  });
});

/* ------------------------------------------------------------------ */
/* Tone                                                               */
/* ------------------------------------------------------------------ */

describe("matchTone", () => {
  it("puts a drawn elimination series in its own state, not in done", () => {
    const match = fakeMatch({ status: "done", needsDecision: true });
    expect(matchTone(match)).toBe("decision");
    expect(matchToneNote(match)).toBe("Needs a winner");
  });

  it("says nothing about a match that is simply not played, or simply over", () => {
    expect(matchToneNote(fakeMatch({ status: "pending" }))).toBeNull();
    expect(matchToneNote(fakeMatch({ status: "done" }))).toBeNull();
  });

  it("calls a skipped bracket reset not needed rather than hiding it", () => {
    const match = fakeMatch({ status: "void", skipped: true });
    expect(matchTone(match)).toBe("void");
    expect(matchToneNote(match)).toBe("Not needed");
  });

  it("flags a live match", () => {
    expect(matchToneNote(fakeMatch({ status: "live" }))).toBe("In progress");
  });
});

/* ------------------------------------------------------------------ */
/* Shape                                                              */
/* ------------------------------------------------------------------ */

describe("hasBracketShape", () => {
  it("is true for an elimination stage and false for a pure table", () => {
    expect(hasBracketShape(blankEight())).toBe(true);

    const table = generateStage("round_robin", 4, {});
    const resolved = resolveMatches({
      stage: table,
      matches: blankRecords(table),
      teams: makeTeams(4),
    });
    expect(hasBracketShape(resolved)).toBe(false);
  });
});

/* ------------------------------------------------------------------ */
/* Up next                                                            */
/* ------------------------------------------------------------------ */

describe("upNext", () => {
  it("takes the first pending matches in board order on an untouched bracket", () => {
    const matches = blankEight();
    expect(upNext(matches).map((match) => match.slot)).toEqual(["ubqf1", "ubqf2", "ubqf3"]);
  });

  it("does not let a later match with a start time jump an earlier one without", () => {
    const matches = blankEight();
    matches[3].scheduledAt = "2026-09-12T10:00:00.000Z";
    expect(upNext(matches, 1)[0].slot).toBe("ubqf1");
  });

  it("puts anything live in front of anything pending", () => {
    const matches = blankEight();
    matches[2].status = "live";
    expect(upNext(matches, 1)[0].slot).toBe("ubqf3");
  });

  it("puts a stalled decision in front of everything, because it is blocking", () => {
    const matches = blankEight();
    matches[2].status = "live";
    matches[5].needsDecision = true;
    expect(upNext(matches, 2).map((match) => match.slot)).toEqual(["ubsf2", "ubqf3"]);
  });

  it("never lists the same match twice", () => {
    const matches = blankEight();
    matches[0].status = "live";
    matches[0].needsDecision = true;
    const slots = upNext(matches, 8).map((match) => match.slot);
    expect(new Set(slots).size).toBe(slots.length);
  });
});

/* ------------------------------------------------------------------ */
/* Podium                                                             */
/* ------------------------------------------------------------------ */

describe("podiumEntries", () => {
  it("names the top three in words and orders by position", () => {
    const entries = podiumEntries([
      { position: 2, shared: 1, teamId: "t2" },
      { position: 1, shared: 1, teamId: "t1" },
      { position: 3, shared: 1, teamId: "t3" },
      { position: 4, shared: 1, teamId: "t4" },
    ]);
    expect(entries.map((entry) => entry.label)).toEqual([
      "Champion",
      "Runner-up",
      "Bronze",
      "4th",
    ]);
    expect(entries[0].teamId).toBe("t1");
  });

  it("prints a shared block as the range it is", () => {
    const [entry] = podiumEntries([{ position: 5, shared: 2, teamId: "t5" }], 1);
    expect(entry.label).toBe("5th–6th");
  });

  it("takes a real eight-team double elimination all the way to joint seventh", () => {
    const stage = generateStage("double_elim", 8, {});
    const played = playStage(stage);
    const entries = podiumEntries(played.resolution.placements(), 8);

    expect(entries).toHaveLength(8);
    expect(entries[0].label).toBe("Champion");
    expect(entries.map((entry) => entry.label).slice(4)).toEqual([
      "5th–6th",
      "5th–6th",
      "7th–8th",
      "7th–8th",
    ]);
    // Better seeds win throughout, so seed 1 lifts it.
    expect(entries[0].teamId).toBe("t1");
  });

  it("has no champion while the final is still to be played", () => {
    expect(championOf([])).toBeNull();
    expect(championOf([{ position: 1, shared: 1, teamId: "t1" }])).toBe("t1");
  });
});

/* ------------------------------------------------------------------ */
/* Results                                                            */
/* ------------------------------------------------------------------ */

describe("resultsLog", () => {
  it("shows nothing at all on an untouched bracket", () => {
    expect(resultsLog(blankEight())).toEqual([]);
    expect(gamesPlayed(blankEight())).toBe(0);
  });

  it("reads forwards even when the results were recorded out of order", () => {
    const early = fakeMatch({
      slot: "late-record",
      status: "done",
      finishedAt: "2026-09-12T12:00:00.000Z",
      games: [game({ played: true })],
    });
    const later = fakeMatch({
      slot: "early-record",
      status: "done",
      finishedAt: "2026-09-12T16:00:00.000Z",
      games: [game({ played: true })],
    });
    expect(resultsLog([later, early]).map((m) => m.slot)).toEqual([
      "late-record",
      "early-record",
    ]);
  });

  it("falls back to the scheduled time, then to board order", () => {
    const scheduled = fakeMatch({
      slot: "scheduled",
      status: "done",
      scheduledAt: "2026-09-12T09:00:00.000Z",
      games: [game({ played: true })],
    });
    const neither = fakeMatch({ slot: "neither", status: "done", games: [game({ played: true })] });
    expect(resultsLog([neither, scheduled]).map((m) => m.slot)).toEqual([
      "scheduled",
      "neither",
    ]);
  });

  it("counts every game across the log", () => {
    const stage = generateStage("round_robin", 4, {});
    const records = blankRecords(stage);
    winSeries(records[0], "a");
    drawSeries(records[1]);
    const matches = resolveMatches({ stage, matches: records, teams: makeTeams(4) });

    expect(resultsLog(matches)).toHaveLength(2);
    expect(gamesPlayed(matches)).toBe(2);
  });
});

/* ------------------------------------------------------------------ */
/* Days, in the reader's zone                                         */
/* ------------------------------------------------------------------ */

describe("groupByDay", () => {
  const plan = { a: 1, b: 1, c: 2 } as const;

  it("keeps a session that overruns past midnight on the day it started", () => {
    // 22:30 UTC is 00:30 the next morning in Budapest — a different calendar
    // day, and still the same evening to everybody playing it.
    const a = fakeMatch({ slot: "a", scheduledAt: "2026-09-12T16:00:00.000Z" });
    const b = fakeMatch({ slot: "b", scheduledAt: "2026-09-12T22:30:00.000Z" });
    const { days } = groupByDay([a, b], plan);

    expect(days).toHaveLength(1);
    expect(days[0].day).toBe(1);
    expect(days[0].matches.map((match) => match.slot)).toEqual(["a", "b"]);
  });

  it("splits on the organiser's day, not on the clock", () => {
    const a = fakeMatch({ slot: "a", scheduledAt: "2026-09-12T16:00:00.000Z" });
    const c = fakeMatch({ slot: "c", scheduledAt: "2026-09-13T16:00:00.000Z" });
    const { days } = groupByDay([c, a], plan);

    expect(days.map((day) => day.day)).toEqual([1, 2]);
    expect(days[0].startsAt).toBe("2026-09-12T16:00:00.000Z");
    expect(days[1].matches.map((match) => match.slot)).toEqual(["c"]);
  });

  it("accepts the Map that dayBySlot hands back as well as a plain object", () => {
    const a = fakeMatch({ slot: "a", scheduledAt: "2026-09-12T16:00:00.000Z" });
    const c = fakeMatch({ slot: "c", scheduledAt: "2026-09-13T16:00:00.000Z" });
    const asMap = new Map(Object.entries(plan));

    expect(groupByDay([a, c], asMap).days.map((day) => day.day)).toEqual([1, 2]);
  });

  it("orders a day by the clock and keeps board order for a shared lobby slot", () => {
    const first = fakeMatch({ slot: "a", scheduledAt: "2026-09-12T16:00:00.000Z" });
    const same = fakeMatch({ slot: "b", scheduledAt: "2026-09-12T16:00:00.000Z" });
    const later = fakeMatch({ slot: "c", scheduledAt: "2026-09-12T18:00:00.000Z" });
    // `c` is day 2 in the plan, so put everything on day 1 for this one.
    const { days } = groupByDay([later, first, same], { a: 1, b: 1, c: 1 });

    expect(days).toHaveLength(1);
    expect(days[0].matches.map((match) => match.slot)).toEqual(["a", "b", "c"]);
    expect(days[0].startsAt).toBe("2026-09-12T16:00:00.000Z");
  });

  it("hands back unscheduled matches rather than dropping them", () => {
    const dated = fakeMatch({ slot: "a", scheduledAt: "2026-09-12T16:00:00.000Z" });
    const undated = fakeMatch({ slot: "b" });
    const result = groupByDay([dated, undated], plan);

    expect(result.days).toHaveLength(1);
    expect(result.undated.map((match) => match.slot)).toEqual(["b"]);
  });

  it("treats an unparseable stamp as unscheduled instead of inventing a day", () => {
    const broken = fakeMatch({ slot: "a", scheduledAt: "not a date" });
    expect(groupByDay([broken], plan).undated.map((match) => match.slot)).toEqual(["a"]);
  });

  it("puts a slot the plan never mentioned on day 1 rather than in limbo", () => {
    const stray = fakeMatch({ slot: "unknown", scheduledAt: "2026-09-12T16:00:00.000Z" });
    const { days, undated } = groupByDay([stray], plan);

    expect(undated).toEqual([]);
    expect(days.map((day) => day.day)).toEqual([1]);
  });

  it("lays a real two-day plan out in the days the scheduler chose", () => {
    const stage = generateStage("double_elim", 8, {});
    const blocks = planBlocks([stage], { days: 2, concurrentLobbies: 2 });
    const matches = resolveMatches({
      stage,
      matches: blankRecords(stage).map((record) => ({
        ...record,
        scheduledAt: "2026-09-12T16:00:00.000Z",
      })),
      teams: makeTeams(8),
    });

    const { days } = groupByDay(matches, dayBySlot(blocks));
    expect(days.map((day) => day.day)).toEqual([1, 2]);
    // Every match lands somewhere, and nowhere twice.
    expect(days.reduce((total, day) => total + day.matches.length, 0)).toBe(matches.length);
  });
});

/* ------------------------------------------------------------------ */
/* Standings                                                          */
/* ------------------------------------------------------------------ */

describe("tableStarted", () => {
  it("is false while every row is still on nothing", () => {
    const stage = generateStage("round_robin", 4, {});
    const records = blankRecords(stage);
    const teams = makeTeams(4);
    const untouched = resolveMatches({ stage, matches: records, teams });
    expect(untouched).toHaveLength(6);

    const { resolution } = playStage(stage, { teams });
    expect(tableStarted(resolution.table(null))).toBe(true);
  });
});
