import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { generateStage } from "@/lib/bracket";
import { type ResolvedMatch, resolveMatches } from "@/lib/format-resolve";
import {
  blankRecords,
  drawSeries,
  makeTeams,
  playStage,
  winSeries,
} from "@/lib/__tests__/format-helpers";
import MatchCard from "../MatchCard";

/**
 * The card's "Side and map" list, and the one question it has to answer
 * without being asked: is this series over?
 *
 * §8.4 swaps the side and map roles every game, so the answer is printed per
 * game rather than per match, and a game nobody has played yet is exactly the
 * game whose answer is still wanted (UC-19 2, R-80). The defect this file
 * pins is what that rule did once the series stopped: a Bo3 won 2–0 kept
 * printing `G3 — Team 1 picks the side · Team 4 picks the map`, future tense,
 * in the same classes as the two games that were actually played, on an event
 * that had been over for a month. A live semi at 1–0 beside it printed the
 * identical shape, so the list hid the one distinction it was best placed to
 * make (R-79 / the bracket and results pages).
 *
 * The fixtures are real stages generated by `src/lib/bracket.ts` and resolved
 * by `src/lib/format-resolve.ts`, like `board.test.ts`'s — the interesting
 * states here (a drawn decider frozen on `needsDecision`, a bracket reset the
 * grand final voided) are states the resolver decides, and a hand-written
 * `ResolvedMatch` could be given a combination it would never produce.
 *
 * Everything is asserted against the rendered markup rather than a helper,
 * because the rule lives in the component: every pure function it calls —
 * `choiceLine`, `choiceRecap`, `matchTone` — is as correct today as it was
 * while the bug was on screen.
 */

/** A four-team single elimination, Bo3 throughout (no Bo5 final to special-case). */
function semisStage() {
  return generateStage("single_elim", 4, { bestOf: 3, bestOfBySlot: {} });
}

function resolve(records: ReturnType<typeof blankRecords>, stage = semisStage()) {
  return resolveMatches({ stage, matches: records, teams: makeTeams(4) });
}

/** Semi 1 taken 2–0 — two games played, a third that will never be. */
function wonTwoNil(): ResolvedMatch {
  const stage = semisStage();
  const records = blankRecords(stage);
  winSeries(records[0], "a");
  return resolve(records, stage)[0];
}

/** Semi 1 at 1–0, still being played. */
function liveOneNil(): ResolvedMatch {
  const stage = semisStage();
  const records = blankRecords(stage);
  const first = records[0].games[0];
  first.scoreA = 1;
  first.scoreB = 0;
  first.played = true;
  return resolve(records, stage)[0];
}

/** Every game in, nobody ahead, no override yet: the state that is *not* decided. */
function frozenOnADraw(): ResolvedMatch {
  const stage = semisStage();
  const records = blankRecords(stage);
  drawSeries(records[0]);
  return resolve(records, stage)[0];
}

/** One drawn game and an admin naming the winner — decided without being won. */
function decidedByOverride(): ResolvedMatch {
  const stage = semisStage();
  const records = blankRecords(stage);
  const first = records[0].games[0];
  first.scoreA = 1;
  first.scoreB = 1;
  first.played = true;
  records[0].winnerOverrideId = "t1";
  return resolve(records, stage)[0];
}

/**
 * A stale override on a drawn game 1: decided, unwon, and two games still to play.
 *
 * `frozenOnADraw` cannot pin the rule it looks like it pins. `drawSeries`
 * plays every game, so `filter(wasPlayed)` is a no-op on it and a card that
 * wrongly counted `decision` as settled would return the same three rows. The
 * state that tells them apart needs `needsDecision` *and* an unplayed game,
 * and this is how the resolver reaches it: an override naming a team that is
 * not in this match is a form left over from another one, so it is ignored
 * (`format-resolve.ts`, `computeOutcome`), while `isMatchDecided` has already
 * said "decided" on the strength of the override existing. Decided, nobody
 * won, games 2 and 3 never played — and an admin still owed a winner.
 */
function frozenWithGamesLeft(): ResolvedMatch {
  const stage = semisStage();
  const records = blankRecords(stage);
  const first = records[0].games[0];
  first.scoreA = 1;
  first.scoreB = 1;
  first.played = true;
  // t2 is seeded into semi 2, so this override names nobody who is playing here.
  records[0].winnerOverrideId = "t2";
  const match = resolve(records, stage)[0];
  if (match.teamAId === "t2" || match.teamBId === "t2") {
    throw new Error("fixture: t2 plays in this match, so the override is not stale");
  }
  return match;
}

/** A live 1–0 with the side taken written down — the recap's other wording (R-82). */
function sideRecorded(): ResolvedMatch {
  const stage = semisStage();
  const records = blankRecords(stage);
  const first = records[0].games[0];
  first.scoreA = 1;
  first.scoreB = 0;
  first.played = true;
  first.sideChosen = "attack";
  return resolve(records, stage)[0];
}

/** The bracket reset the grand final made unnecessary — no winner, and nothing to play. */
function voidedReset(): ResolvedMatch {
  const stage = generateStage("double_elim", 4, { bracketReset: true });
  const match = playStage(stage).matches.find((m) => m.skipped);
  if (!match) throw new Error("fixture: the grand final did not void the reset");
  return match;
}

function render(match: ResolvedMatch, compact = false): string {
  // `renderToStaticMarkup` emits no hydration comments, but a text node split
  // by an interpolation ("G" + index) is not worth depending on either way.
  return renderToStaticMarkup(createElement(MatchCard, { match, compact })).replaceAll(
    "<!-- -->",
    ""
  );
}

/**
 * The game labels of the side-and-map rows, in order.
 *
 * Both lists on the card are `G1`, `G2`, … rows, so they are told apart by
 * position and shape: the side-and-map list is drawn first, and the played-
 * games list after it prints a score in every row, which nothing in a choice
 * row does.
 *
 * Deliberately **not** by wording. This used to keep the rows containing "the
 * side", which holds only while no game has a side recorded: `choiceRecap`
 * drops that wording entirely the moment a manager writes down which side was
 * taken (R-82 — "Team 1 took attack · Team 4 picked the map"). Every fixture
 * here leaves `sideChosen` null, so it passed; the first realistic fixture to
 * record one would have made its own played rows invisible to the reader, and
 * a test failing because its reader cannot see a row that is on screen reads
 * like the card dropped it. `sideRecorded` below pins that.
 */
function choiceRows(markup: string): string[] {
  const first = /<ul[^>]*>([\s\S]*?)<\/ul>/.exec(markup)?.[1];
  if (first === undefined || first.includes('class="num')) return [];
  return [...first.matchAll(/>G(\d+)</g)].map(([, index]) => `G${index}`);
}

describe("a decided series", () => {
  it("lists only the games it played — a Bo3 won 2–0 stops at G2", () => {
    const markup = render(wonTwoNil());

    expect(choiceRows(markup)).toEqual(["G1", "G2"]);
    // The row itself, not just its label: G3 was printed as a promise.
    expect(markup).not.toContain("picks the side");
    expect(markup).toContain("picked the side");
  });

  it("stops at G2 in a compact bracket column too", () => {
    const markup = render(wonTwoNil(), true);

    expect(choiceRows(markup)).toEqual(["G1", "G2"]);
    expect(markup).not.toContain("picks the side");
    // Compact drops the heading, not the list, and that is unchanged.
    expect(markup).not.toContain("Side and map");
  });

  it("is decided by an admin's override as surely as by a scoreline", () => {
    // One drawn game, then a winner named by hand: games 2 and 3 are as dead
    // as game 3 of a 2–0, and neither `winner` nor the games alone say so.
    expect(choiceRows(render(decidedByOverride()))).toEqual(["G1"]);
  });

  it("keeps the heading and the border only while a row survives", () => {
    // A voided bracket reset has no winner at all, so a `winner !== null` test
    // would leave all five rows standing under "Not needed".
    const markup = render(voidedReset());

    expect(choiceRows(markup)).toEqual([]);
    expect(markup).not.toContain("Side and map");
    expect(markup).toContain("Not needed");
  });
});

describe("a series that is still going", () => {
  it("lists the games to come, in the future tense — a live Bo3 at 1–0 keeps G2 and G3", () => {
    const markup = render(liveOneNil());

    expect(choiceRows(markup)).toEqual(["G1", "G2", "G3"]);
    expect(markup).toContain("picks the side");
    expect(markup).toContain("picked the side");
  });

  it("keeps every row of a series frozen on a drawn decider", () => {
    // Decided by the games and won by nobody: the resolver calls this `live`
    // with `needsDecision`, never `done`, and the card must not shorten it.
    const match = frozenOnADraw();
    const markup = render(match);

    expect(match.needsDecision).toBe(true);
    expect(choiceRows(markup)).toEqual(["G1", "G2", "G3"]);
    expect(markup).toContain("Needs a winner");
  });

  it("keeps every row when the decision landed with games still unplayed", () => {
    // The assertion `frozenOnADraw` only looks like it makes. Mutating the
    // card's guard to `done || void || decision` — deliberately breaking this
    // rule — leaves that test green and kills this one: here two of the three
    // games were never played, so a card that treated `decision` as settled
    // would come back with G1 alone.
    const match = frozenWithGamesLeft();
    const markup = render(match);

    expect(match.needsDecision).toBe(true);
    expect(match.games.filter((game) => game.played)).toHaveLength(1);
    expect(choiceRows(markup)).toEqual(["G1", "G2", "G3"]);
    expect(markup).toContain("Needs a winner");
  });

  it("still lists a played row once the side taken is on record", () => {
    // Not about the card at all: it is what stops `choiceRows` from quietly
    // going blind on the realistic fixture. A recorded side rewrites the recap
    // (R-82), and the wording the reader used to select on disappears with it.
    const markup = render(sideRecorded());

    expect(markup).toContain("took attack");
    expect(markup).not.toContain("picked the side");
    expect(choiceRows(markup)).toEqual(["G1", "G2", "G3"]);
  });

  it("lists the whole series on a match nobody has started", () => {
    const pending = resolve(blankRecords(semisStage()))[2];

    expect(pending.status).toBe("pending");
    expect(choiceRows(render(pending))).toEqual(["G1", "G2", "G3"]);
  });
});
